export const DOCKER_COMPOSE_KEYWORDS = [
  { label: "version", type: "keyword", detail: "Docker Compose file version" },
  { label: "services", type: "keyword", detail: "Service definitions" },
  { label: "volumes", type: "keyword", detail: "Volume definitions" },
  { label: "networks", type: "keyword", detail: "Network definitions" },
  { label: "image", type: "keyword", detail: "Docker image to use" },
  { label: "build", type: "keyword", detail: "Build configuration" },
  { label: "ports", type: "keyword", detail: "Port mapping" },
  { label: "environment", type: "keyword", detail: "Environment variables" },
  { label: "env_file", type: "keyword", detail: "Environment file" },
  { label: "volumes", type: "keyword", detail: "Volumes to mount" },
  { label: "networks", type: "keyword", detail: "Networks to use" },
  { label: "depends_on", type: "keyword", detail: "Service dependencies" },
  { label: "restart", type: "keyword", detail: "Restart policy" },
  { label: "command", type: "keyword", detail: "Command to execute" },
  { label: "entrypoint", type: "keyword", detail: "Container entrypoint" },
  { label: "working_dir", type: "keyword", detail: "Working directory" },
  { label: "user", type: "keyword", detail: "User to run the container" },
  { label: "healthcheck", type: "keyword", detail: "Health check configuration" },
  { label: "deploy", type: "keyword", detail: "Deployment configuration" },
  { label: "labels", type: "keyword", detail: "Container labels" },
  { label: "logging", type: "keyword", detail: "Logging configuration" },
  { label: "secrets", type: "keyword", detail: "Secrets to use" },
  { label: "configs", type: "keyword", detail: "Configurations to use" },
  { label: "profiles", type: "keyword", detail: "Deployment profiles" },
  { label: "extends", type: "keyword", detail: "Configuration inheritance" },
  { label: "external", type: "keyword", detail: "External resource" },
  { label: "driver", type: "keyword", detail: "Driver to use" },
  { label: "driver_opts", type: "keyword", detail: "Driver options" },
  { label: "name", type: "keyword", detail: "Resource name" },
  { label: "aliases", type: "keyword", detail: "Network aliases" },
  { label: "ipv4_address", type: "keyword", detail: "IPv4 address" },
  { label: "ipv6_address", type: "keyword", detail: "IPv6 address" },
  { label: "links", type: "keyword", detail: "Container links" },
  { label: "expose", type: "keyword", detail: "Exposed ports" },
  { label: "tmpfs", type: "keyword", detail: "Tmpfs mount" },
  { label: "pid", type: "keyword", detail: "PID namespace" },
  { label: "dns", type: "keyword", detail: "DNS servers" },
  { label: "dns_search", type: "keyword", detail: "DNS search domain" },
  { label: "dns_opt", type: "keyword", detail: "DNS options" },
  { label: "extra_hosts", type: "keyword", detail: "Additional hosts" },
  { label: "cap_add", type: "keyword", detail: "Add capabilities" },
  { label: "cap_drop", type: "keyword", detail: "Drop capabilities" },
  { label: "security_opt", type: "keyword", detail: "Security options" },
  { label: "stop_grace_period", type: "keyword", detail: "Graceful stop period" },
  { label: "stop_signal", type: "keyword", detail: "Stop signal" },
  { label: "sysctls", type: "keyword", detail: "Sysctl parameters" },
  { label: "ulimits", type: "keyword", detail: "System limits" },
  { label: "read_only", type: "keyword", detail: "Read-only mode" },
  { label: "tty", type: "keyword", detail: "Allocate TTY" },
  { label: "stdin_open", type: "keyword", detail: "Open STDIN" },
  { label: "privileged", type: "keyword", detail: "Privileged mode" },
  { label: "shm_size", type: "keyword", detail: "Size of /dev/shm" },
  { label: "init", type: "keyword", detail: "Use init" },
  { label: "isolation", type: "keyword", detail: "Container isolation" },
  { label: "platform", type: "keyword", detail: "Target platform" },
  { label: "pull_policy", type: "keyword", detail: "Pull policy" },
  { label: "scale", type: "keyword", detail: "Number of instances" },
  { label: "update_config", type: "keyword", detail: "Update configuration" },
  { label: "rollback_config", type: "keyword", detail: "Rollback configuration" },
  { label: "resources", type: "keyword", detail: "Allocated resources" },
  { label: "reservations", type: "keyword", detail: "Resource reservations" },
  { label: "restart_policy", type: "keyword", detail: "Restart policy" },
  { label: "placement", type: "keyword", detail: "Container placement" },
  { label: "constraints", type: "keyword", detail: "Placement constraints" },
  { label: "preferences", type: "keyword", detail: "Placement preferences" },
  { label: "replicas", type: "keyword", detail: "Number of replicas" },
  { label: "mode", type: "keyword", detail: "Deployment mode" },
  { label: "endpoint_mode", type: "keyword", detail: "Endpoint mode" },
  { label: "ports", type: "keyword", detail: "Exposed ports" },
  { label: "configs", type: "keyword", detail: "Configurations" },
  { label: "secrets", type: "keyword", detail: "Secrets" },
  { label: "x-", type: "keyword", detail: "Extension (prefix for custom extensions)" },
]; 